name: Deploy latest build
on: 
  push:
    branches: [ master ]
permissions:
  contents: write
    
jobs:
  deploy-build:
  runs-on: ubuntu-latest
  steps:
    name: Deploy 🚀
    uses: JamesIves/github-pages-deploy-action@v4
    with: 
      folder: build
    
